// Generated by gencpp from file music_client/playmusic.msg
// DO NOT EDIT!


#ifndef MUSIC_CLIENT_MESSAGE_PLAYMUSIC_H
#define MUSIC_CLIENT_MESSAGE_PLAYMUSIC_H

#include <ros/service_traits.h>


#include <music_client/playmusicRequest.h>
#include <music_client/playmusicResponse.h>


namespace music_client
{

struct playmusic
{

typedef playmusicRequest Request;
typedef playmusicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct playmusic
} // namespace music_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::music_client::playmusic > {
  static const char* value()
  {
    return "3d99283888736c5e18f20ac685e5f8bf";
  }

  static const char* value(const ::music_client::playmusic&) { return value(); }
};

template<>
struct DataType< ::music_client::playmusic > {
  static const char* value()
  {
    return "music_client/playmusic";
  }

  static const char* value(const ::music_client::playmusic&) { return value(); }
};


// service_traits::MD5Sum< ::music_client::playmusicRequest> should match
// service_traits::MD5Sum< ::music_client::playmusic >
template<>
struct MD5Sum< ::music_client::playmusicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::music_client::playmusic >::value();
  }
  static const char* value(const ::music_client::playmusicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::music_client::playmusicRequest> should match
// service_traits::DataType< ::music_client::playmusic >
template<>
struct DataType< ::music_client::playmusicRequest>
{
  static const char* value()
  {
    return DataType< ::music_client::playmusic >::value();
  }
  static const char* value(const ::music_client::playmusicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::music_client::playmusicResponse> should match
// service_traits::MD5Sum< ::music_client::playmusic >
template<>
struct MD5Sum< ::music_client::playmusicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::music_client::playmusic >::value();
  }
  static const char* value(const ::music_client::playmusicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::music_client::playmusicResponse> should match
// service_traits::DataType< ::music_client::playmusic >
template<>
struct DataType< ::music_client::playmusicResponse>
{
  static const char* value()
  {
    return DataType< ::music_client::playmusic >::value();
  }
  static const char* value(const ::music_client::playmusicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUSIC_CLIENT_MESSAGE_PLAYMUSIC_H
