// Generated by gencpp from file file_transfer/FileTransferRequest.msg
// DO NOT EDIT!


#ifndef FILE_TRANSFER_MESSAGE_FILETRANSFERREQUEST_H
#define FILE_TRANSFER_MESSAGE_FILETRANSFERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace file_transfer
{
template <class ContainerAllocator>
struct FileTransferRequest_
{
  typedef FileTransferRequest_<ContainerAllocator> Type;

  FileTransferRequest_()
    : source_path()
    , target_path()
    , is_download(false)
    , file_data()
    , success(false)
    , message()
    , file_size(0)  {
    }
  FileTransferRequest_(const ContainerAllocator& _alloc)
    : source_path(_alloc)
    , target_path(_alloc)
    , is_download(false)
    , file_data(_alloc)
    , success(false)
    , message(_alloc)
    , file_size(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_path_type;
  _source_path_type source_path;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_path_type;
  _target_path_type target_path;

   typedef uint8_t _is_download_type;
  _is_download_type is_download;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _file_data_type;
  _file_data_type file_data;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef int64_t _file_size_type;
  _file_size_type file_size;





  typedef boost::shared_ptr< ::file_transfer::FileTransferRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::file_transfer::FileTransferRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FileTransferRequest_

typedef ::file_transfer::FileTransferRequest_<std::allocator<void> > FileTransferRequest;

typedef boost::shared_ptr< ::file_transfer::FileTransferRequest > FileTransferRequestPtr;
typedef boost::shared_ptr< ::file_transfer::FileTransferRequest const> FileTransferRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::file_transfer::FileTransferRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::file_transfer::FileTransferRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::file_transfer::FileTransferRequest_<ContainerAllocator1> & lhs, const ::file_transfer::FileTransferRequest_<ContainerAllocator2> & rhs)
{
  return lhs.source_path == rhs.source_path &&
    lhs.target_path == rhs.target_path &&
    lhs.is_download == rhs.is_download &&
    lhs.file_data == rhs.file_data &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.file_size == rhs.file_size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::file_transfer::FileTransferRequest_<ContainerAllocator1> & lhs, const ::file_transfer::FileTransferRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace file_transfer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::file_transfer::FileTransferRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::file_transfer::FileTransferRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::file_transfer::FileTransferRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::file_transfer::FileTransferRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::file_transfer::FileTransferRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::file_transfer::FileTransferRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::file_transfer::FileTransferRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f6b3d4d49e3b3db7a6ad1ca13631528";
  }

  static const char* value(const ::file_transfer::FileTransferRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f6b3d4d49e3b3dbULL;
  static const uint64_t static_value2 = 0x7a6ad1ca13631528ULL;
};

template<class ContainerAllocator>
struct DataType< ::file_transfer::FileTransferRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "file_transfer/FileTransferRequest";
  }

  static const char* value(const ::file_transfer::FileTransferRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::file_transfer::FileTransferRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"string source_path    # 源文件路径(调用方指定)\n"
"string target_path    # 目标文件路径(服务端指定)\n"
"bool is_download      # true=下位机->上位机(下载), false=上位机->下位机(上传)\n"
"uint8[] file_data     # 文件数据(二进制)\n"
"\n"
"# Response\n"
"bool success\n"
"string message\n"
"int64 file_size\n"
"\n"
;
  }

  static const char* value(const ::file_transfer::FileTransferRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::file_transfer::FileTransferRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.source_path);
      stream.next(m.target_path);
      stream.next(m.is_download);
      stream.next(m.file_data);
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.file_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FileTransferRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::file_transfer::FileTransferRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::file_transfer::FileTransferRequest_<ContainerAllocator>& v)
  {
    s << indent << "source_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source_path);
    s << indent << "target_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target_path);
    s << indent << "is_download: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_download);
    s << indent << "file_data[]" << std::endl;
    for (size_t i = 0; i < v.file_data.size(); ++i)
    {
      s << indent << "  file_data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.file_data[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "file_size: ";
    Printer<int64_t>::stream(s, indent + "  ", v.file_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FILE_TRANSFER_MESSAGE_FILETRANSFERREQUEST_H
