// Generated by gencpp from file file_transfer/FileTransferResponse.msg
// DO NOT EDIT!


#ifndef FILE_TRANSFER_MESSAGE_FILETRANSFERRESPONSE_H
#define FILE_TRANSFER_MESSAGE_FILETRANSFERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace file_transfer
{
template <class ContainerAllocator>
struct FileTransferResponse_
{
  typedef FileTransferResponse_<ContainerAllocator> Type;

  FileTransferResponse_()
    {
    }
  FileTransferResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::file_transfer::FileTransferResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::file_transfer::FileTransferResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FileTransferResponse_

typedef ::file_transfer::FileTransferResponse_<std::allocator<void> > FileTransferResponse;

typedef boost::shared_ptr< ::file_transfer::FileTransferResponse > FileTransferResponsePtr;
typedef boost::shared_ptr< ::file_transfer::FileTransferResponse const> FileTransferResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::file_transfer::FileTransferResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::file_transfer::FileTransferResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace file_transfer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::file_transfer::FileTransferResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::file_transfer::FileTransferResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::file_transfer::FileTransferResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::file_transfer::FileTransferResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::file_transfer::FileTransferResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::file_transfer::FileTransferResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::file_transfer::FileTransferResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::file_transfer::FileTransferResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::file_transfer::FileTransferResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "file_transfer/FileTransferResponse";
  }

  static const char* value(const ::file_transfer::FileTransferResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::file_transfer::FileTransferResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::file_transfer::FileTransferResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::file_transfer::FileTransferResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FileTransferResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::file_transfer::FileTransferResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::file_transfer::FileTransferResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FILE_TRANSFER_MESSAGE_FILETRANSFERRESPONSE_H
