// Generated by gencpp from file file_transfer/FileTransfer.msg
// DO NOT EDIT!


#ifndef FILE_TRANSFER_MESSAGE_FILETRANSFER_H
#define FILE_TRANSFER_MESSAGE_FILETRANSFER_H

#include <ros/service_traits.h>


#include <file_transfer/FileTransferRequest.h>
#include <file_transfer/FileTransferResponse.h>


namespace file_transfer
{

struct FileTransfer
{

typedef FileTransferRequest Request;
typedef FileTransferResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FileTransfer
} // namespace file_transfer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::file_transfer::FileTransfer > {
  static const char* value()
  {
    return "1f6b3d4d49e3b3db7a6ad1ca13631528";
  }

  static const char* value(const ::file_transfer::FileTransfer&) { return value(); }
};

template<>
struct DataType< ::file_transfer::FileTransfer > {
  static const char* value()
  {
    return "file_transfer/FileTransfer";
  }

  static const char* value(const ::file_transfer::FileTransfer&) { return value(); }
};


// service_traits::MD5Sum< ::file_transfer::FileTransferRequest> should match
// service_traits::MD5Sum< ::file_transfer::FileTransfer >
template<>
struct MD5Sum< ::file_transfer::FileTransferRequest>
{
  static const char* value()
  {
    return MD5Sum< ::file_transfer::FileTransfer >::value();
  }
  static const char* value(const ::file_transfer::FileTransferRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::file_transfer::FileTransferRequest> should match
// service_traits::DataType< ::file_transfer::FileTransfer >
template<>
struct DataType< ::file_transfer::FileTransferRequest>
{
  static const char* value()
  {
    return DataType< ::file_transfer::FileTransfer >::value();
  }
  static const char* value(const ::file_transfer::FileTransferRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::file_transfer::FileTransferResponse> should match
// service_traits::MD5Sum< ::file_transfer::FileTransfer >
template<>
struct MD5Sum< ::file_transfer::FileTransferResponse>
{
  static const char* value()
  {
    return MD5Sum< ::file_transfer::FileTransfer >::value();
  }
  static const char* value(const ::file_transfer::FileTransferResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::file_transfer::FileTransferResponse> should match
// service_traits::DataType< ::file_transfer::FileTransfer >
template<>
struct DataType< ::file_transfer::FileTransferResponse>
{
  static const char* value()
  {
    return DataType< ::file_transfer::FileTransfer >::value();
  }
  static const char* value(const ::file_transfer::FileTransferResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FILE_TRANSFER_MESSAGE_FILETRANSFER_H
