// Generated by gencpp from file kuavo_audio_player/playmusicRequest.msg
// DO NOT EDIT!


#ifndef KUAVO_AUDIO_PLAYER_MESSAGE_PLAYMUSICREQUEST_H
#define KUAVO_AUDIO_PLAYER_MESSAGE_PLAYMUSICREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_audio_player
{
template <class ContainerAllocator>
struct playmusicRequest_
{
  typedef playmusicRequest_<ContainerAllocator> Type;

  playmusicRequest_()
    : music_path()  {
    }
  playmusicRequest_(const ContainerAllocator& _alloc)
    : music_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _music_path_type;
  _music_path_type music_path;





  typedef boost::shared_ptr< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> const> ConstPtr;

}; // struct playmusicRequest_

typedef ::kuavo_audio_player::playmusicRequest_<std::allocator<void> > playmusicRequest;

typedef boost::shared_ptr< ::kuavo_audio_player::playmusicRequest > playmusicRequestPtr;
typedef boost::shared_ptr< ::kuavo_audio_player::playmusicRequest const> playmusicRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_audio_player::playmusicRequest_<ContainerAllocator1> & lhs, const ::kuavo_audio_player::playmusicRequest_<ContainerAllocator2> & rhs)
{
  return lhs.music_path == rhs.music_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_audio_player::playmusicRequest_<ContainerAllocator1> & lhs, const ::kuavo_audio_player::playmusicRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_audio_player

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2d09829452828247b2631028a949bf3";
  }

  static const char* value(const ::kuavo_audio_player::playmusicRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2d0982945282824ULL;
  static const uint64_t static_value2 = 0x7b2631028a949bf3ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_audio_player/playmusicRequest";
  }

  static const char* value(const ::kuavo_audio_player::playmusicRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string music_path\n"
;
  }

  static const char* value(const ::kuavo_audio_player::playmusicRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.music_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct playmusicRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_audio_player::playmusicRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_audio_player::playmusicRequest_<ContainerAllocator>& v)
  {
    s << indent << "music_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.music_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_AUDIO_PLAYER_MESSAGE_PLAYMUSICREQUEST_H
