// Generated by gencpp from file musicplayer_pkg/playmusic.msg
// DO NOT EDIT!


#ifndef MUSICPLAYER_PKG_MESSAGE_PLAYMUSIC_H
#define MUSICPLAYER_PKG_MESSAGE_PLAYMUSIC_H

#include <ros/service_traits.h>


#include <musicplayer_pkg/playmusicRequest.h>
#include <musicplayer_pkg/playmusicResponse.h>


namespace musicplayer_pkg
{

struct playmusic
{

typedef playmusicRequest Request;
typedef playmusicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct playmusic
} // namespace musicplayer_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::musicplayer_pkg::playmusic > {
  static const char* value()
  {
    return "3d99283888736c5e18f20ac685e5f8bf";
  }

  static const char* value(const ::musicplayer_pkg::playmusic&) { return value(); }
};

template<>
struct DataType< ::musicplayer_pkg::playmusic > {
  static const char* value()
  {
    return "musicplayer_pkg/playmusic";
  }

  static const char* value(const ::musicplayer_pkg::playmusic&) { return value(); }
};


// service_traits::MD5Sum< ::musicplayer_pkg::playmusicRequest> should match
// service_traits::MD5Sum< ::musicplayer_pkg::playmusic >
template<>
struct MD5Sum< ::musicplayer_pkg::playmusicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::musicplayer_pkg::playmusic >::value();
  }
  static const char* value(const ::musicplayer_pkg::playmusicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::musicplayer_pkg::playmusicRequest> should match
// service_traits::DataType< ::musicplayer_pkg::playmusic >
template<>
struct DataType< ::musicplayer_pkg::playmusicRequest>
{
  static const char* value()
  {
    return DataType< ::musicplayer_pkg::playmusic >::value();
  }
  static const char* value(const ::musicplayer_pkg::playmusicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::musicplayer_pkg::playmusicResponse> should match
// service_traits::MD5Sum< ::musicplayer_pkg::playmusic >
template<>
struct MD5Sum< ::musicplayer_pkg::playmusicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::musicplayer_pkg::playmusic >::value();
  }
  static const char* value(const ::musicplayer_pkg::playmusicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::musicplayer_pkg::playmusicResponse> should match
// service_traits::DataType< ::musicplayer_pkg::playmusic >
template<>
struct DataType< ::musicplayer_pkg::playmusicResponse>
{
  static const char* value()
  {
    return DataType< ::musicplayer_pkg::playmusic >::value();
  }
  static const char* value(const ::musicplayer_pkg::playmusicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUSICPLAYER_PKG_MESSAGE_PLAYMUSIC_H
